#ifndef WA_Common_Enums_H
#define WA_Common_Enums_H

/// <summary>
/// Defines WinAudio Errors code
/// </summary>
enum WINAUDIO_ERRORS
{
	WINAUDIO_OK = 0,
	WINAUDIO_FILENOTFOUND,
	WINAUDIO_FILENOTSUPPORTED,
	WINAUDIO_FILENOTOPEN,
	WINAUDIO_OUTPUTNOTREADY,
	WINAUDIO_MALLOCFAIL,
	WINAUDIO_PBTHREADCREATIONFAIL,
	WINAUDIO_EVENTSCREATIONFAIL,
	WINAUDIO_INVALIDOUTPUT,
	WINAUDIO_BADPTR,
	WINAUDIO_CANNOTPLAYFILE,
	WINAUDIO_CANNOTCHANGESTATUS,
	WINAUDIO_STREAMNOTSEEKABLE,
	WINAUDIO_REQUESTFAIL,
	WINAUDIO_OUTOFBUFFER

};

/// <summary>
/// Define Avaiable Outputs mode
/// </summary>
enum WINAUDIO_OUTPUT
{
	WINAUDIO_WASAPI = 0,
	WINAUDIO_DIRECTSOUND
};

/// <summary>
/// Define Playback Status
/// </summary>
enum WINAUDIO_PLAYBACK_STATUS
{
	WINAUDIO_PLAY = 0,
	WINAUDIO_PAUSE,
	WINAUDIO_STOP
};

/// <summary>
/// Define FFT Sample Size (power of 2)
/// </summary>
enum WINAUDIO_FFT_SIZE
{
	WINAUDIO_FFT_512 =	512,
	WINAUDIO_FFT_1024 = 1024,
	WINAUDIO_FFT_2048 = 2048,
	WINAUDIO_FFT_4096 = 4096,
	WINAUDIO_FFT_8192 = 8192
};

#endif
